# Generated by Django 5.0.3 on 2024-04-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("commune_name", models.CharField(max_length=255)),
                ("commune_name_ascii", models.CharField(max_length=255)),
                ("daira_name", models.CharField(max_length=255)),
                ("daira_name_ascii", models.CharField(max_length=255)),
                ("wilaya_code", models.CharField(max_length=4)),
                ("wilaya_name", models.CharField(max_length=255)),
                ("wilaya_name_ascii", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "algeria_cities",
            },
        ),
    ]
