name: algeria-cities python lib

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    defaults:
      run:
        working-directory: ./python

        
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install the project dependencies
        run: poetry install

      - name: Run unittests
        working-directory: ./python
        run: poetry run pytest tests -s
